# Generated by Django 2.0 on 2019-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='HomeAddress',
            field=models.CharField(default='', max_length=800),
        ),
    ]
