# Generated by Django 2.0 on 2019-06-07 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fl_app', '0006_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typework', models.CharField(max_length=200)),
                ('startdate', models.DateField(default=datetime.date(2019, 6, 8))),
                ('enddate', models.DateField(blank=True, null=True)),
                ('fname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fname', to=settings.AUTH_USER_MODEL)),
                ('lname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='relation',
            name='fname',
        ),
        migrations.DeleteModel(
            name='relation',
        ),
    ]
