# Generated by Django 2.0 on 2019-06-08 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0007_auto_20190607_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frtable',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 6, 9)),
        ),
        migrations.AlterField(
            model_name='lrtable',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 6, 9)),
        ),
        migrations.AlterField(
            model_name='relation1',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 6, 9)),
        ),
    ]
