# Generated by Django 2.0 on 2019-06-08 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fl_app', '0008_auto_20190608_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmercheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=datetime.date(2019, 6, 9))),
                ('typework', models.CharField(max_length=200)),
                ('fname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fname1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='labourcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=datetime.date(2019, 6, 9))),
                ('lname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lname1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
