# Generated by Django 2.0 on 2019-06-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_app', '0009_farmercheck_labourcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercheck',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
